// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pb/caves_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCavesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaveIds       []int32                `protobuf:"varint,1,rep,packed,name=cave_ids,json=caveIds,proto3" json:"cave_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCavesRequest) Reset() {
	*x = GetCavesRequest{}
	mi := &file_pb_caves_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCavesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCavesRequest) ProtoMessage() {}

func (x *GetCavesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_caves_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCavesRequest.ProtoReflect.Descriptor instead.
func (*GetCavesRequest) Descriptor() ([]byte, []int) {
	return file_pb_caves_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCavesRequest) GetCaveIds() []int32 {
	if x != nil {
		return x.CaveIds
	}
	return nil
}

type GetCavesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caves         []*Cave                `protobuf:"bytes,1,rep,name=caves,proto3" json:"caves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCavesResponse) Reset() {
	*x = GetCavesResponse{}
	mi := &file_pb_caves_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCavesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCavesResponse) ProtoMessage() {}

func (x *GetCavesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_caves_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCavesResponse.ProtoReflect.Descriptor instead.
func (*GetCavesResponse) Descriptor() ([]byte, []int) {
	return file_pb_caves_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCavesResponse) GetCaves() []*Cave {
	if x != nil {
		return x.Caves
	}
	return nil
}

type Cave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      *LatLng                `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cave) Reset() {
	*x = Cave{}
	mi := &file_pb_caves_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cave) ProtoMessage() {}

func (x *Cave) ProtoReflect() protoreflect.Message {
	mi := &file_pb_caves_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cave.ProtoReflect.Descriptor instead.
func (*Cave) Descriptor() ([]byte, []int) {
	return file_pb_caves_service_proto_rawDescGZIP(), []int{2}
}

func (x *Cave) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cave) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Cave) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cave) GetLocation() *LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

type LatLng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	mi := &file_pb_caves_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_pb_caves_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_pb_caves_service_proto_rawDescGZIP(), []int{3}
}

func (x *LatLng) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LatLng) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_pb_caves_service_proto protoreflect.FileDescriptor

const file_pb_caves_service_proto_rawDesc = "" +
	"\n" +
	"\x16pb/caves_service.proto\x12\x02pb\",\n" +
	"\x0fGetCavesRequest\x12\x19\n" +
	"\bcave_ids\x18\x01 \x03(\x05R\acaveIds\"2\n" +
	"\x10GetCavesResponse\x12\x1e\n" +
	"\x05caves\x18\x01 \x03(\v2\b.pb.CaveR\x05caves\"~\n" +
	"\x04Cave\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\blocation\x18\x04 \x01(\v2\n" +
	".pb.LatLngR\blocation\"B\n" +
	"\x06LatLng\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude2G\n" +
	"\fCavesService\x127\n" +
	"\bGetCaves\x12\x13.pb.GetCavesRequest\x1a\x14.pb.GetCavesResponse\"\x00B2Z0github.com/KMankowski/CaveTrack-Cave/internal/pbb\x06proto3"

var (
	file_pb_caves_service_proto_rawDescOnce sync.Once
	file_pb_caves_service_proto_rawDescData []byte
)

func file_pb_caves_service_proto_rawDescGZIP() []byte {
	file_pb_caves_service_proto_rawDescOnce.Do(func() {
		file_pb_caves_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_caves_service_proto_rawDesc), len(file_pb_caves_service_proto_rawDesc)))
	})
	return file_pb_caves_service_proto_rawDescData
}

var file_pb_caves_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_caves_service_proto_goTypes = []any{
	(*GetCavesRequest)(nil),  // 0: pb.GetCavesRequest
	(*GetCavesResponse)(nil), // 1: pb.GetCavesResponse
	(*Cave)(nil),             // 2: pb.Cave
	(*LatLng)(nil),           // 3: pb.LatLng
}
var file_pb_caves_service_proto_depIdxs = []int32{
	2, // 0: pb.GetCavesResponse.caves:type_name -> pb.Cave
	3, // 1: pb.Cave.location:type_name -> pb.LatLng
	0, // 2: pb.CavesService.GetCaves:input_type -> pb.GetCavesRequest
	1, // 3: pb.CavesService.GetCaves:output_type -> pb.GetCavesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_caves_service_proto_init() }
func file_pb_caves_service_proto_init() {
	if File_pb_caves_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_caves_service_proto_rawDesc), len(file_pb_caves_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_caves_service_proto_goTypes,
		DependencyIndexes: file_pb_caves_service_proto_depIdxs,
		MessageInfos:      file_pb_caves_service_proto_msgTypes,
	}.Build()
	File_pb_caves_service_proto = out.File
	file_pb_caves_service_proto_goTypes = nil
	file_pb_caves_service_proto_depIdxs = nil
}
