// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: pb/caves_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CavesService_GetCaves_FullMethodName = "/pb.CavesService/GetCaves"
)

// CavesServiceClient is the client API for CavesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CavesServiceClient interface {
	GetCaves(ctx context.Context, in *GetCavesRequest, opts ...grpc.CallOption) (*GetCavesResponse, error)
}

type cavesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCavesServiceClient(cc grpc.ClientConnInterface) CavesServiceClient {
	return &cavesServiceClient{cc}
}

func (c *cavesServiceClient) GetCaves(ctx context.Context, in *GetCavesRequest, opts ...grpc.CallOption) (*GetCavesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCavesResponse)
	err := c.cc.Invoke(ctx, CavesService_GetCaves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CavesServiceServer is the server API for CavesService service.
// All implementations must embed UnimplementedCavesServiceServer
// for forward compatibility.
type CavesServiceServer interface {
	GetCaves(context.Context, *GetCavesRequest) (*GetCavesResponse, error)
	mustEmbedUnimplementedCavesServiceServer()
}

// UnimplementedCavesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCavesServiceServer struct{}

func (UnimplementedCavesServiceServer) GetCaves(context.Context, *GetCavesRequest) (*GetCavesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaves not implemented")
}
func (UnimplementedCavesServiceServer) mustEmbedUnimplementedCavesServiceServer() {}
func (UnimplementedCavesServiceServer) testEmbeddedByValue()                      {}

// UnsafeCavesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CavesServiceServer will
// result in compilation errors.
type UnsafeCavesServiceServer interface {
	mustEmbedUnimplementedCavesServiceServer()
}

func RegisterCavesServiceServer(s grpc.ServiceRegistrar, srv CavesServiceServer) {
	// If the following call pancis, it indicates UnimplementedCavesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CavesService_ServiceDesc, srv)
}

func _CavesService_GetCaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CavesServiceServer).GetCaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CavesService_GetCaves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CavesServiceServer).GetCaves(ctx, req.(*GetCavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CavesService_ServiceDesc is the grpc.ServiceDesc for CavesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CavesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CavesService",
	HandlerType: (*CavesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCaves",
			Handler:    _CavesService_GetCaves_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/caves_service.proto",
}
